service:
  name: spike-serverless-to-ec2

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - schedule: cron(0/1 * * * ? *)
