service:
  name: spike-serverless-to-ec2

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:Start*
        - ec2:Stop*
      Resource:
        - '*'

functions:
  hello:
    handler: handler.hello
    events:
      - schedule: cron(* 1 * * ? *)
  start:
    handler: handler.start
    events:
      - schedule: cron(0 1 * * ? *)
  stop:
    handler: handler.stop
    events:
      - schedule: cron(0 2 * * ? *)
